name: CI_CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Continuous-Integration:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1   
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Install Docker Compose
      run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
   
    - name: Validate configuration
      run: docker-compose config

    #- name: Build Docker image
      #run: |
        #docker-compose build

    #- name: Build Docker image
      #run: docker buildx web:latest .

    #-  name: Tag Docker image
       #run: |
        #IMAGE_NAME="rajes1976/testdemo:v1"
        #docker tag web $IMAGE_NAME
    
    #- name: Push Docker image to Docker Hub
      #run: |
        #IMAGE_NAME="rajes1976/testdemo:v1"
        #docker push $IMAGE_NAME
    
    - name: Run Docker Compose
      run: docker-compose up -d

    - name: Test network connectivity
      run: |
        docker-compose up -d
        sleep 10
        docker exec proxy-server curl -I http://webserver

  #Continuous-Delivery:
    #needs: Continuous-Integration
    #runs-on: self-hosted
 
    #steps:
      #- name: Check out repository
        #uses: actions/checkout@v3
 
      #- name: Run docker-compose
        #run: docker-compose up -d
