name: CI_CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Continuous-Integration:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1   
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Install Docker Compose
      run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
   
    - name: Validate configuration
      run: docker-compose config
      
    - name: Run Docker Compose
      run: docker-compose up -d

    - name: Test network connectivity
      run: |
        docker-compose up -d
        sleep 10
        docker exec proxy-server curl -I http://webserver
         
    - name: Build Docker Images
      run: docker-compose build

    - name: List Docker images
      run: docker images
          
    - name: Push Docker Images to Docker Hub
      run: |
        IMAGE_NAME_1="rajes1976/webserver:v2"
        IMAGE_NAME_2="rajes1976/jsapp:v2"
        docker tag rajes1976/webserver:v1 $IMAGE_NAME_1
        docker tag rajes1976/jsapp:v1 $IMAGE_NAME_2  
        docker push $IMAGE_NAME_1
        docker push $IMAGE_NAME_2 

  Continuous-Delivery:
    needs: Continuous-Integration
    runs-on: self-hosted
 
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker Images from Docker Hub
        run: |
          docker pull rajes1976/webserver:v2
          docker pull rajes1976/jsapp:v2

      - name: Pull Docker Images from Docker Hub
        run: |
          docker-compose pull

      -  name: Build Docker images
         run: docker-compose build
      
      - name: Run docker-compose
        run: docker-compose up -d --force-recreate
