name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: ~/caches
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build Docker image
      uses: actions/cache@v2
      with:
        path: ~/caches
        context: .
        push: true
        tags: rajes1976/project:v1.0
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - uses: actions/checkout@v2
    - name: Build the Docker Web image
      run: docker build . --file dockerfile --tag my-image-name:$(date +%s)

    - uses: actions/checkout@v2
    - name: Build the Docker nodejs image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    - uses: actions/checkout@v2
    - name: Build the Docker Compose image
      run: docker build . --file docker-compose.yml  

    - name: Run Docker Compose
      run: docker-compose up -d

    - name: Validate configuration
      run: docker-compose config

    - name: Test network connectivity
      run: |
        docker-compose up -d
        sleep 10
        docker exec <proxy-server> ping -c 4 <webserver>
